### ISSUE TITLE
Lab_MPL : Episode 1 - масштаб по осям

### ISSUE THREAD

**Issue by avasyukov** [ItsMyPain/3-sem#1]
Сейчас масштаб по осям разный по OX и по OY. В итоге, например, длинная и тонкая область визуально выглядит как почти квадратик. А условный кружочек превращается в эллипс.

В условии было, что масштаб должен быть зафиксирован. Это нужно поправить.

**Comment by ItsMyPain** [comment]
Ready

**Comment by avasyukov** [comment]
Confirmed
