### ISSUE TITLE
Lab_MPL : Episode 2 - странная работа с тиками

### ISSUE THREAD

**Issue by avasyukov** [ItsMyPain/3-sem#2]
Вот тут:
https://github.com/ItsMyPain/3-sem/blob/53102ebc9954d17b7883bb3ef9aa9ca26a4410c5/Lab_MPL/Episode%202/main.py#L22-L27
кажется, многовато лишних движений.

1. Если тики неразличимы, зачем отдельно major-ы и minor-ы?
2. Если все подписи одинаковые, бегать в цикле по отдельным тикам кажется избыточным. Можно выставить размер и прочие параметры массово. (Любой разумный рецепт с https://stackoverflow.com/questions/6390393/matplotlib-make-tick-labels-font-size-smaller, например.)

**Comment by ItsMyPain** [comment]
Complete

**Comment by avasyukov** [comment]
Confirmed
