### ISSUE TITLE
Lab_MPL : Episode 2 - большой объём дублирования кода

### ISSUE THREAD

**Issue by avasyukov** [ItsMyPain/3-sem#3]
Вот тут:
https://github.com/ItsMyPain/3-sem/blob/53102ebc9954d17b7883bb3ef9aa9ca26a4410c5/Lab_MPL/Episode%202/main.py#L40-L62
явно лишняя копипаста.

Всё понятно, что она возникла из-за того, что хочется кадры отдельно сохранить для gif-ки. Но всё же не надо так. Можно, например, построение картинки со всеми её параметрами в функции унести. Можно ещё что-нибудь придумать.

**Comment by ItsMyPain** [comment]
Completed

**Comment by avasyukov** [comment]
Confirmed
